# Generated by Django 5.1.6 on 2026-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaly', '0002_rename_usario_alimentacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='quantidade_planejada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treino',
            name='quantidade_realizada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
