# Generated by Django 6.0.3 on 2026-03-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitaly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentacao',
            old_name='usario',
            new_name='usuario',
        ),
    ]
