# Generated by Django 4.2.16 on 2026-04-13 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitaly', '0004_alter_alimentacao_id_alter_estudo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentacao',
            old_name='classificacao',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='alimentacao',
            name='horarios',
        ),
        migrations.RemoveField(
            model_name='estudo',
            name='horas_estudo',
        ),
        migrations.RemoveField(
            model_name='sono',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudo',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treino',
            name='quantidade_planejada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treino',
            name='quantidade_realizada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LogMetricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hidratacao', 'Hidratação'), ('alimentacao', 'Alimentação')], max_length=20)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sono', 'Sono'), ('estudo', 'Estudo'), ('treino', 'Treino')], max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
